// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using BerberYonetimSistemi.Models;
using BerberYonetimSistemi.Data;

#nullable disable

namespace BerberYonetimSistemi.Migrations
{
    [DbContext(typeof(BerberDbContext))]
    [Migration("20241203140900_RandevuTablosuEkle")]
    partial class RandevuTablosuEkle
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BerberYonetimSistemi.Models.Randevu", b =>
                {
                    b.Property<int>("RandevuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RandevuId"));

                    b.Property<int>("CalisanId")
                        .HasColumnType("integer");

                    b.Property<int>("IslemId")
                        .HasColumnType("integer");

                    b.Property<string>("MusteriAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MusteriTelefon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RandevuTarih")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RandevuId");

                    b.ToTable("Randevular");
                });
#pragma warning restore 612, 618
        }
    }
}
