// <auto-generated />
using System;
using BerberYonetimSistemi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BerberYonetimSistemi.Migrations
{
    [DbContext(typeof(BerberDbContext))]
    partial class BerberDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BerberYonetimSistemi.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AdminId"));

                    b.Property<string>("AdminAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AdminEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AdminSoyadi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AdminTelefon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AdminId");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("BerberYonetimSistemi.Models.Berber", b =>
                {
                    b.Property<int>("BerberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BerberId"));

                    b.Property<string>("BerberAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("BerberId");

                    b.ToTable("Berberler");
                });

            modelBuilder.Entity("BerberYonetimSistemi.Models.Calisan", b =>
                {
                    b.Property<int>("CalisanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CalisanId"));

                    b.Property<int>("BerberId")
                        .HasColumnType("integer");

                    b.Property<string>("CalisanAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CalisanSoyadi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CalisanTelefon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CalisanId");

                    b.HasIndex("BerberId");

                    b.ToTable("Calisanlar");
                });

            modelBuilder.Entity("BerberYonetimSistemi.Models.Kullanici", b =>
                {
                    b.Property<int>("KullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KullaniciId"));

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KullaniciSifre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KullaniciSifreTekrar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KullaniciSoyadi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KullaniciTelefon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("KullaniciId");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("BerberYonetimSistemi.Models.Randevu", b =>
                {
                    b.Property<int>("RandevuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RandevuId"));

                    b.Property<int>("BerberId")
                        .HasColumnType("integer");

                    b.Property<int>("CalisanId")
                        .HasColumnType("integer");

                    b.Property<int>("IslemId")
                        .HasColumnType("integer");

                    b.Property<string>("MusteriAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MusteriTelefon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RandevuSaati")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RandevuTarih")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RandevuId");

                    b.HasIndex("BerberId");

                    b.HasIndex("CalisanId");

                    b.ToTable("Randevular");
                });

            modelBuilder.Entity("BerberYonetimSistemi.Models.Calisan", b =>
                {
                    b.HasOne("BerberYonetimSistemi.Models.Berber", "Berber")
                        .WithMany("Calisanlar")
                        .HasForeignKey("BerberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Berber");
                });

            modelBuilder.Entity("BerberYonetimSistemi.Models.Randevu", b =>
                {
                    b.HasOne("BerberYonetimSistemi.Models.Berber", "Berber")
                        .WithMany()
                        .HasForeignKey("BerberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BerberYonetimSistemi.Models.Calisan", "Calisan")
                        .WithMany()
                        .HasForeignKey("CalisanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Berber");

                    b.Navigation("Calisan");
                });

            modelBuilder.Entity("BerberYonetimSistemi.Models.Berber", b =>
                {
                    b.Navigation("Calisanlar");
                });
#pragma warning restore 612, 618
        }
    }
}
